name: Greetings

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup-java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: maven
        run: mvn clean install