name: Greetings

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup-java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: maven install
        run: cd java-app && mvn clean install
      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: demo
          path: java-app/target/demo-0.0.1-SNAPSHOT.jar