name: Action Commands
on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Test composite
        uses: ./.github/actions/compose-action/action.yml@main
        with:
          skip-tests: true